# Generated by Django 4.0.6 on 2022-08-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_comment_user_alter_comment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publishing_date']},
        ),
    ]
